# Site settings
title: Git for Librarians Shared Recipes
email: chris-diaz@northwestern.edu
description: The plain text recipe database for hackers
baseurl: "https://chrisdaaz.github.io/forking/"
language: "en"
lang_direction: "ltr"
color: "#007FFF"
twitter_username: chrisdaaz
github_username:  chrisdaaz

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

translation:
  en:
    ingredients: "Ingredients"
    directions: "Directions"
    category: "Category"
    nutritional_information: "Nutritional Information"
    component_based: 'This is a <strong class="blue">component-based recipe</strong>.'
    search: "Search"
    subscribe: "Subscribe"
  de:
    ingredients: "Zutaten"
    directions: "Zubereitung"
    category: "Kategorie"
    nutritional_information: "NÃ¤hrwertangaben"
    component_based: 'Dieses Rezept besteht aus <strong class="blue">mehreren Komponenten</strong>.'
    search: "Suche"
    subscribe: "Abonnieren"
